Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"

    # Para conectar na VM1 via ssh
    # Entrar na ssh da vm2
    # ssh vagrant@192.168.56.10
    # yes
    config.vm.define "vm2" do |vm2|
        vm2.vm.hostname = "vm2"
        vm2.vm.provider "virtualbox" do |vb|
            vb.name = "VM2"
            vb.memory = 1024
            vb.cpus = 1
        end
        
        vm2.vm.synced_folder "../app", "/var/www/app"
        vm2.vm.network "private_network", ip: "192.168.56.20"
        vm2.vm.provision "shell", path: "scripts/setup-node.sh"
        vm2.vm.provision "shell", path: "scripts/key-generate.sh"
        vm2.vm.provision "shell", path: "scripts/save-key.sh"
    end

    # Jenkins - senha inicial do admin:
    # sudo cat /var/lib/jenkins/secrets/initialAdminPassword
    config.vm.define "vm1" do |vm1|
        vm1.vm.hostname = "vm1"
        vm1.vm.provider "virtualbox" do |vb|
            vb.name = "VM1"
            vb.memory = 1024
            vb.cpus = 1
        end

        vm1.vm.network "forwarded_port", guest: 8080, host: 8050
        vm1.vm.network "private_network", ip: "192.168.56.10"
        vm1.vm.provision "shell", path: "scripts/setup-node.sh"
        vm1.vm.provision "shell", path: "scripts/setup-java-jenkins.sh"
        vm1.vm.provision "shell", path: "scripts/add-key.sh"
    end

end